### ISSUE TITLE
Řešení rozstřelu 14.06.2023, 8. otázka

### ISSUE THREAD

**Issue by vojta-horanek** [marakujaa/FIT-matika#2]
![image](https://github.com/marakujaa/FIT-matika/assets/12630566/e5172de1-7a52-49b0-9317-5f96989a4f65)

V posledním bodě jsou spatně vybrané podposloupnosti, nemají stejnou limitu, jak to otázka vyžaduje.

**Comment by marakujaa** [comment]
Opraveno, děkuji!
